// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: "http://localhost:8081" | (string & {})
}

/**
 * AlbumDiscDto
 */
export type AlbumDiscDto = {
    /**
     * Id
     */
    id: number
    /**
     * Disc Number
     */
    disc_number: number
    /**
     * Track Count
     */
    track_count: number
    /**
     * Tracks
     */
    tracks: Array<AlbumTrackDto>
}

/**
 * AlbumDto
 */
export type AlbumDto = {
    /**
     * Id
     */
    id: number
    /**
     * Title
     */
    title: string
    /**
     * Artists
     */
    artists: Array<ArtistWithNameDto>
    /**
     * Release Year
     */
    release_year: number | null
    artwork: CoverArtDto | null
}

/**
 * AlbumMusicbrainzDetailsDto
 */
export type AlbumMusicbrainzDetailsDto = {
    /**
     * Mbid
     */
    mbid: string
    /**
     * Release Type
     */
    release_type: string
    /**
     * Release Date
     */
    release_date: string
    /**
     * Labels
     */
    labels: Array<MusicbrainzLabelDto>
    /**
     * Genres
     */
    genres: Array<MusicbrainzGenreDto>
}

/**
 * AlbumTrackDto
 */
export type AlbumTrackDto = {
    /**
     * Id
     */
    id: number
    /**
     * Title
     */
    title: string
    /**
     * Release Year
     */
    release_year: number
    /**
     * Duration
     */
    duration: number
    /**
     * Artists
     */
    artists: Array<ArtistWithNameDto>
    /**
     * Features
     */
    features: Array<ArtistWithNameDto>
    /**
     * Remixers
     */
    remixers: Array<ArtistWithNameDto>
    musical_features: AlbumTrackMusicalFeaturesDto | null
    artwork: CoverArtDto | null
    /**
     * Track Number
     */
    track_number: number
}

/**
 * AlbumTrackMusicalFeaturesDto
 */
export type AlbumTrackMusicalFeaturesDto = {
    /**
     * Bpm
     */
    bpm: number
    /**
     * Key
     */
    key: string
    /**
     * Scale
     */
    scale: string
    /**
     * Camelot Index
     */
    camelot_index: number
}

/**
 * AlbumWithDetailsDto
 */
export type AlbumWithDetailsDto = {
    /**
     * Id
     */
    id: number
    /**
     * Title
     */
    title: string
    /**
     * Artists
     */
    artists: Array<ArtistWithNameDto>
    /**
     * Release Year
     */
    release_year: number | null
    /**
     * Discs
     */
    discs: Array<AlbumDiscDto>
    artwork: CoverArtDto | null
    mb_details: AlbumMusicbrainzDetailsDto | null
}

/**
 * AlbumsResponse
 */
export type AlbumsResponse = {
    /**
     * Albums
     */
    albums: Array<AlbumDto>
}

/**
 * ArtistWithDetailsDto
 */
export type ArtistWithDetailsDto = {
    /**
     * Id
     */
    id: number
    /**
     * Name
     */
    name: string
    /**
     * Album Count
     */
    album_count: number
    /**
     * Track Count
     */
    track_count: number
    /**
     * Feature Count
     */
    feature_count: number
    /**
     * Remix Count
     */
    remix_count: number
    /**
     * Production Credit Count
     */
    production_credit_count: number
    /**
     * Writing Credit Count
     */
    writing_credit_count: number
    artwork: CoverArtDto | null
}

/**
 * ArtistWithNameDto
 */
export type ArtistWithNameDto = {
    /**
     * Id
     */
    id: number
    /**
     * Name
     */
    name: string
    artwork: CoverArtDto | null
}

/**
 * ArtistsResponse
 */
export type ArtistsResponse = {
    /**
     * Artists
     */
    artists: Array<ArtistWithDetailsDto>
}

/**
 * Body_put_artist_cover_art_library_artists__artist_id__cover_art_post
 */
export type BodyPutArtistCoverArtLibraryArtistsArtistIdCoverArtPost = {
    /**
     * File
     */
    file: Blob | File
}

/**
 * CoverArtDto
 */
export type CoverArtDto = {
    /**
     * Id
     */
    id: number
    /**
     * Accent Color
     */
    accent_color: string
}

/**
 * DiscDto
 */
export type DiscDto = {
    /**
     * Id
     */
    id: number
    /**
     * Disc Number
     */
    disc_number: number
    /**
     * Track Count
     */
    track_count: number
    album: AlbumDto
}

/**
 * DiscTrackDto
 */
export type DiscTrackDto = {
    disc: DiscDto
    /**
     * Track Number
     */
    track_number: number
}

/**
 * DiscsResponse
 */
export type DiscsResponse = {
    /**
     * Discs
     */
    discs: Array<DiscDto>
}

/**
 * FolderAddRequest
 */
export type FolderAddRequest = {
    /**
     * Path
     */
    path: string
}

/**
 * FolderDto
 */
export type FolderDto = {
    /**
     * Id
     */
    id: number
    /**
     * Path
     */
    path: string
    /**
     * Invalid Reason
     */
    invalid_reason: string
    /**
     * Track Count
     */
    track_count: number
}

/**
 * FoldersResponse
 */
export type FoldersResponse = {
    /**
     * Folders
     */
    folders: Array<FolderDto>
}

/**
 * LyricsSettingsDto
 */
export type LyricsSettingsDto = {
    /**
     * Fetch Lyrics
     */
    fetch_lyrics: boolean
    /**
     * Lrclib Api Url
     */
    lrclib_api_url: string
}

/**
 * LyricsSettingsUpdateRequest
 */
export type LyricsSettingsUpdateRequest = {
    /**
     * Fetch Lyrics
     */
    fetch_lyrics?: boolean | null
    /**
     * Lrclib Api Url
     */
    lrclib_api_url?: string | null
}

/**
 * MusicalAnalysisLevel
 */
export type MusicalAnalysisLevel = "none" | "basic" | "full"

/**
 * MusicalAnalysisSettingsDto
 */
export type MusicalAnalysisSettingsDto = {
    level: MusicalAnalysisLevel
}

/**
 * MusicalAnalysisSettingsUpdateRequest
 */
export type MusicalAnalysisSettingsUpdateRequest = {
    level?: MusicalAnalysisLevel | null
}

/**
 * MusicbrainzGenreDto
 */
export type MusicbrainzGenreDto = {
    /**
     * Name
     */
    name: string
}

/**
 * MusicbrainzLabelDto
 */
export type MusicbrainzLabelDto = {
    /**
     * Mbid
     */
    mbid: string
    /**
     * Name
     */
    name: string
    /**
     * Type
     */
    type: string
}

/**
 * MusicbrainzSettingsDto
 */
export type MusicbrainzSettingsDto = {
    /**
     * Fetch Data
     */
    fetch_data: boolean
    /**
     * Mb Api Hostname
     */
    mb_api_hostname: string
}

/**
 * MusicbrainzSettingsUpdateRequest
 */
export type MusicbrainzSettingsUpdateRequest = {
    /**
     * Fetch Data
     */
    fetch_data?: boolean | null
    /**
     * Mb Api Hostname
     */
    mb_api_hostname?: string | null
}

/**
 * NoSplitEntriesResponse
 */
export type NoSplitEntriesResponse = {
    /**
     * Entries
     */
    entries: Array<NoSplitEntryDto>
}

/**
 * NoSplitEntryDto
 */
export type NoSplitEntryDto = {
    /**
     * Id
     */
    id: number
    /**
     * Name
     */
    name: string
}

/**
 * NoSplitUpsertRequest
 */
export type NoSplitUpsertRequest = {
    /**
     * Name
     */
    name: string
}

/**
 * OngoingOperationStatus
 */
export type OngoingOperationStatus =
    | "enqueued"
    | "started"
    | "completed"
    | "failed"
    | "skipped"

/**
 * PlaylistAddTrackRequest
 */
export type PlaylistAddTrackRequest = {
    /**
     * Track Id
     */
    track_id: number
}

/**
 * PlaylistCreateRequest
 */
export type PlaylistCreateRequest = {
    /**
     * Name
     */
    name: string
}

/**
 * PlaylistDto
 */
export type PlaylistDto = {
    /**
     * Id
     */
    id: number
    /**
     * Name
     */
    name: string
    /**
     * Author
     */
    author: string
    /**
     * Created At
     */
    created_at: string
    /**
     * Updated At
     */
    updated_at: string
    /**
     * Track Count
     */
    track_count: number
}

/**
 * PlaylistTrackDto
 */
export type PlaylistTrackDto = {
    /**
     * Id
     */
    id: number
    track: TrackDto
}

/**
 * PlaylistWithTracksDto
 */
export type PlaylistWithTracksDto = {
    /**
     * Id
     */
    id: number
    /**
     * Name
     */
    name: string
    /**
     * Author
     */
    author: string
    /**
     * Created At
     */
    created_at: string
    /**
     * Updated At
     */
    updated_at: string
    /**
     * Playlist Tracks
     */
    playlist_tracks: Array<PlaylistTrackDto>
}

/**
 * PlaylistsResponse
 */
export type PlaylistsResponse = {
    /**
     * Playlists
     */
    playlists: Array<PlaylistDto>
}

/**
 * ScanDto
 */
export type ScanDto = {
    /**
     * Id
     */
    id: number
    status: ScanStatus
    /**
     * Enqueued At
     */
    enqueued_at: string
    /**
     * Started At
     */
    started_at: string | null
    /**
     * Ended At
     */
    ended_at: string | null
    tracks_import: ScanTracksImportDto | null
    /**
     * Musical Estimations
     */
    musical_estimations: Array<ScanTrackMusicalEstimationDto> | null
    /**
     * Lyrics
     */
    lyrics: Array<ScanTrackLyricsDto> | null
}

/**
 * ScanSettingsDto
 */
export type ScanSettingsDto = {
    /**
     * Extract Track Features
     */
    extract_track_features: boolean
    /**
     * Split Artists
     */
    split_artists: boolean
}

/**
 * ScanSettingsUpdateRequest
 */
export type ScanSettingsUpdateRequest = {
    /**
     * Extract Track Features
     */
    extract_track_features?: boolean | null
    /**
     * Split Artists
     */
    split_artists?: boolean | null
}

/**
 * ScanStatus
 */
export type ScanStatus = "started" | "completed" | "failed" | "interrupted"

/**
 * ScanTrackLyricsDto
 */
export type ScanTrackLyricsDto = {
    status: OngoingOperationStatus
    /**
     * File Path
     */
    file_path: string
    /**
     * Enqueued At
     */
    enqueued_at: string
    /**
     * Started At
     */
    started_at: string | null
    /**
     * Ended At
     */
    ended_at: string | null
}

/**
 * ScanTrackMusicalEstimationDto
 */
export type ScanTrackMusicalEstimationDto = {
    status: OngoingOperationStatus
    /**
     * File Path
     */
    file_path: string
    /**
     * Enqueued At
     */
    enqueued_at: string
    /**
     * Started At
     */
    started_at: string | null
    /**
     * Ended At
     */
    ended_at: string | null
}

/**
 * ScanTracksImportDto
 */
export type ScanTracksImportDto = {
    status: OngoingOperationStatus
    /**
     * Upserted Tracks
     */
    upserted_tracks: number
    /**
     * Deleted Tracks
     */
    deleted_tracks: number
    /**
     * Enqueued At
     */
    enqueued_at: string
    /**
     * Started At
     */
    started_at: string | null
    /**
     * Ended At
     */
    ended_at: string | null
}

/**
 * ScansResponse
 */
export type ScansResponse = {
    /**
     * Scans
     */
    scans: Array<ScanDto>
}

/**
 * SyncedLyrics
 */
export type SyncedLyrics = {
    /**
     * Lines
     */
    lines: Array<SyncedLyricsLine>
}

/**
 * SyncedLyricsLine
 */
export type SyncedLyricsLine = {
    /**
     * Start
     */
    start: number
    /**
     * End
     */
    end: number
    /**
     * Line
     */
    line: string
}

/**
 * TrackDto
 */
export type TrackDto = {
    /**
     * Id
     */
    id: number
    /**
     * Title
     */
    title: string
    /**
     * Release Year
     */
    release_year: number
    /**
     * Duration
     */
    duration: number
    /**
     * Artists
     */
    artists: Array<ArtistWithNameDto>
    /**
     * Features
     */
    features: Array<ArtistWithNameDto>
    /**
     * Remixers
     */
    remixers: Array<ArtistWithNameDto>
    disc_track: DiscTrackDto | null
    musical_features: TrackMusicalFeaturesDto | null
    /**
     * Has Lyrics
     */
    has_lyrics: boolean
    artwork: CoverArtDto | null
    mb_details: TrackMusicbrainzDetailsDto | null
}

/**
 * TrackLyricsDto
 */
export type TrackLyricsDto = {
    /**
     * Plain Lyrics
     */
    plain_lyrics: string | null
    synced_lyrics: SyncedLyrics | null
}

/**
 * TrackMusicalFeaturesDto
 */
export type TrackMusicalFeaturesDto = {
    /**
     * Bpm
     */
    bpm: number
    /**
     * Key
     */
    key: string
    /**
     * Scale
     */
    scale: string
    /**
     * Camelot Index
     */
    camelot_index: number
}

/**
 * TrackMusicbrainzDetailsDto
 */
export type TrackMusicbrainzDetailsDto = {
    /**
     * Mbid
     */
    mbid: string
    /**
     * Writing Credits
     */
    writing_credits: Array<ArtistWithNameDto>
    /**
     * Production Credits
     */
    production_credits: Array<TrackMusicbrainzProductionCreditDto>
    /**
     * Genres
     */
    genres: Array<MusicbrainzGenreDto>
}

/**
 * TrackMusicbrainzProductionCreditDto
 */
export type TrackMusicbrainzProductionCreditDto = {
    artist: ArtistWithNameDto
    /**
     * Type
     */
    type: string
    /**
     * Description
     */
    description: string
}

/**
 * TrackWaveformDto
 */
export type TrackWaveformDto = {
    /**
     * Waveform
     */
    waveform: Array<number>
}

/**
 * TracksResponse
 */
export type TracksResponse = {
    /**
     * Tracks
     */
    tracks: Array<TrackDto>
}

/**
 * VenusErrorCode
 */
export type VenusErrorCode =
    | "ENTITY_NOT_FOUND"
    | "ENTITY_ALREADY_EXISTS"
    | "UNAUTHORIZED"
    | "FILE_TOO_LARGE"
    | "COULD_NOT_UPLOAD_FILE"
    | "SCAN_ALREADY_ONGOING"
    | "NO_ONGOING_SCAN"
    | "INVALID_FOLDER_PATH"
    | "PATH_ALREADY_COVERED"
    | "PATH_IS_SUPERSET"
    | "PATH_IS_ROOT"
    | "PLAYLIST_BELONGS_TO_ANOTHER_USER"

/**
 * VenusErrorResponse
 */
export type VenusErrorResponse = {
    code: VenusErrorCode
    /**
     * Message
     */
    message: string
}

export type VenusInterruptScanData = {
    body?: never
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null
    }
    path?: never
    query?: never
    url: "/scanning/scans"
}

export type VenusInterruptScanErrors = {
    /**
     * Bad Request
     */
    400: VenusErrorResponse
    /**
     * Unauthorized
     */
    401: VenusErrorResponse
    /**
     * Forbidden
     */
    403: VenusErrorResponse
    /**
     * Not Found
     */
    404: VenusErrorResponse
    /**
     * Conflict
     */
    409: VenusErrorResponse
    /**
     * Unprocessable Entity
     */
    422: VenusErrorResponse
}

export type VenusInterruptScanError =
    VenusInterruptScanErrors[keyof VenusInterruptScanErrors]

export type VenusInterruptScanResponses = {
    /**
     * Successful Response
     */
    200: unknown
}

export type VenusGetAllScansData = {
    body?: never
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null
    }
    path?: never
    query?: never
    url: "/scanning/scans"
}

export type VenusGetAllScansErrors = {
    /**
     * Bad Request
     */
    400: VenusErrorResponse
    /**
     * Unauthorized
     */
    401: VenusErrorResponse
    /**
     * Forbidden
     */
    403: VenusErrorResponse
    /**
     * Not Found
     */
    404: VenusErrorResponse
    /**
     * Conflict
     */
    409: VenusErrorResponse
    /**
     * Unprocessable Entity
     */
    422: VenusErrorResponse
}

export type VenusGetAllScansError =
    VenusGetAllScansErrors[keyof VenusGetAllScansErrors]

export type VenusGetAllScansResponses = {
    /**
     * Successful Response
     */
    200: ScansResponse
}

export type VenusGetAllScansResponse =
    VenusGetAllScansResponses[keyof VenusGetAllScansResponses]

export type VenusRequestScanData = {
    body?: never
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null
    }
    path?: never
    query?: never
    url: "/scanning/scans"
}

export type VenusRequestScanErrors = {
    /**
     * Bad Request
     */
    400: VenusErrorResponse
    /**
     * Unauthorized
     */
    401: VenusErrorResponse
    /**
     * Forbidden
     */
    403: VenusErrorResponse
    /**
     * Not Found
     */
    404: VenusErrorResponse
    /**
     * Conflict
     */
    409: VenusErrorResponse
    /**
     * Unprocessable Entity
     */
    422: VenusErrorResponse
}

export type VenusRequestScanError =
    VenusRequestScanErrors[keyof VenusRequestScanErrors]

export type VenusRequestScanResponses = {
    /**
     * Successful Response
     */
    200: ScanDto
}

export type VenusRequestScanResponse =
    VenusRequestScanResponses[keyof VenusRequestScanResponses]

export type VenusGetRecentScanData = {
    body?: never
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null
    }
    path?: never
    query?: never
    url: "/scanning/scans/recent"
}

export type VenusGetRecentScanErrors = {
    /**
     * Bad Request
     */
    400: VenusErrorResponse
    /**
     * Unauthorized
     */
    401: VenusErrorResponse
    /**
     * Forbidden
     */
    403: VenusErrorResponse
    /**
     * Not Found
     */
    404: VenusErrorResponse
    /**
     * Conflict
     */
    409: VenusErrorResponse
    /**
     * Unprocessable Entity
     */
    422: VenusErrorResponse
}

export type VenusGetRecentScanError =
    VenusGetRecentScanErrors[keyof VenusGetRecentScanErrors]

export type VenusGetRecentScanResponses = {
    /**
     * Successful Response
     */
    200: ScanDto
}

export type VenusGetRecentScanResponse =
    VenusGetRecentScanResponses[keyof VenusGetRecentScanResponses]

export type VenusGetFoldersData = {
    body?: never
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null
    }
    path?: never
    query?: never
    url: "/scanning/folders"
}

export type VenusGetFoldersErrors = {
    /**
     * Bad Request
     */
    400: VenusErrorResponse
    /**
     * Unauthorized
     */
    401: VenusErrorResponse
    /**
     * Forbidden
     */
    403: VenusErrorResponse
    /**
     * Not Found
     */
    404: VenusErrorResponse
    /**
     * Conflict
     */
    409: VenusErrorResponse
    /**
     * Unprocessable Entity
     */
    422: VenusErrorResponse
}

export type VenusGetFoldersError =
    VenusGetFoldersErrors[keyof VenusGetFoldersErrors]

export type VenusGetFoldersResponses = {
    /**
     * Successful Response
     */
    200: FoldersResponse
}

export type VenusGetFoldersResponse =
    VenusGetFoldersResponses[keyof VenusGetFoldersResponses]

export type VenusAddFolderData = {
    body: FolderAddRequest
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null
    }
    path?: never
    query?: never
    url: "/scanning/folders"
}

export type VenusAddFolderErrors = {
    /**
     * Bad Request
     */
    400: VenusErrorResponse
    /**
     * Unauthorized
     */
    401: VenusErrorResponse
    /**
     * Forbidden
     */
    403: VenusErrorResponse
    /**
     * Not Found
     */
    404: VenusErrorResponse
    /**
     * Conflict
     */
    409: VenusErrorResponse
    /**
     * Unprocessable Entity
     */
    422: VenusErrorResponse
}

export type VenusAddFolderError =
    VenusAddFolderErrors[keyof VenusAddFolderErrors]

export type VenusAddFolderResponses = {
    /**
     * Successful Response
     */
    200: FolderDto
}

export type VenusAddFolderResponse =
    VenusAddFolderResponses[keyof VenusAddFolderResponses]

export type VenusDeleteFolderData = {
    body?: never
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null
    }
    path: {
        /**
         * Folder Id
         */
        folder_id: number
    }
    query?: never
    url: "/scanning/folders/{folder_id}"
}

export type VenusDeleteFolderErrors = {
    /**
     * Bad Request
     */
    400: VenusErrorResponse
    /**
     * Unauthorized
     */
    401: VenusErrorResponse
    /**
     * Forbidden
     */
    403: VenusErrorResponse
    /**
     * Not Found
     */
    404: VenusErrorResponse
    /**
     * Conflict
     */
    409: VenusErrorResponse
    /**
     * Unprocessable Entity
     */
    422: VenusErrorResponse
}

export type VenusDeleteFolderError =
    VenusDeleteFolderErrors[keyof VenusDeleteFolderErrors]

export type VenusDeleteFolderResponses = {
    /**
     * Successful Response
     */
    200: unknown
}

export type VenusGetFolderData = {
    body?: never
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null
    }
    path: {
        /**
         * Folder Id
         */
        folder_id: number
    }
    query?: never
    url: "/scanning/folders/{folder_id}"
}

export type VenusGetFolderErrors = {
    /**
     * Bad Request
     */
    400: VenusErrorResponse
    /**
     * Unauthorized
     */
    401: VenusErrorResponse
    /**
     * Forbidden
     */
    403: VenusErrorResponse
    /**
     * Not Found
     */
    404: VenusErrorResponse
    /**
     * Conflict
     */
    409: VenusErrorResponse
    /**
     * Unprocessable Entity
     */
    422: VenusErrorResponse
}

export type VenusGetFolderError =
    VenusGetFolderErrors[keyof VenusGetFolderErrors]

export type VenusGetFolderResponses = {
    /**
     * Successful Response
     */
    200: FolderDto
}

export type VenusGetFolderResponse =
    VenusGetFolderResponses[keyof VenusGetFolderResponses]

export type VenusGetArtistsData = {
    body?: never
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null
    }
    path?: never
    query?: never
    url: "/library/artists"
}

export type VenusGetArtistsErrors = {
    /**
     * Bad Request
     */
    400: VenusErrorResponse
    /**
     * Unauthorized
     */
    401: VenusErrorResponse
    /**
     * Forbidden
     */
    403: VenusErrorResponse
    /**
     * Not Found
     */
    404: VenusErrorResponse
    /**
     * Conflict
     */
    409: VenusErrorResponse
    /**
     * Unprocessable Entity
     */
    422: VenusErrorResponse
}

export type VenusGetArtistsError =
    VenusGetArtistsErrors[keyof VenusGetArtistsErrors]

export type VenusGetArtistsResponses = {
    /**
     * Successful Response
     */
    200: ArtistsResponse
}

export type VenusGetArtistsResponse =
    VenusGetArtistsResponses[keyof VenusGetArtistsResponses]

export type VenusGetArtistData = {
    body?: never
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null
    }
    path: {
        /**
         * Artist Id
         */
        artist_id: number
    }
    query?: never
    url: "/library/artists/{artist_id}"
}

export type VenusGetArtistErrors = {
    /**
     * Bad Request
     */
    400: VenusErrorResponse
    /**
     * Unauthorized
     */
    401: VenusErrorResponse
    /**
     * Forbidden
     */
    403: VenusErrorResponse
    /**
     * Not Found
     */
    404: VenusErrorResponse
    /**
     * Conflict
     */
    409: VenusErrorResponse
    /**
     * Unprocessable Entity
     */
    422: VenusErrorResponse
}

export type VenusGetArtistError =
    VenusGetArtistErrors[keyof VenusGetArtistErrors]

export type VenusGetArtistResponses = {
    /**
     * Successful Response
     */
    200: ArtistWithDetailsDto
}

export type VenusGetArtistResponse =
    VenusGetArtistResponses[keyof VenusGetArtistResponses]

export type VenusPutArtistCoverArtData = {
    body: BodyPutArtistCoverArtLibraryArtistsArtistIdCoverArtPost
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null
    }
    path: {
        /**
         * Artist Id
         */
        artist_id: number
    }
    query?: never
    url: "/library/artists/{artist_id}/cover-art"
}

export type VenusPutArtistCoverArtErrors = {
    /**
     * Bad Request
     */
    400: VenusErrorResponse
    /**
     * Unauthorized
     */
    401: VenusErrorResponse
    /**
     * Forbidden
     */
    403: VenusErrorResponse
    /**
     * Not Found
     */
    404: VenusErrorResponse
    /**
     * Conflict
     */
    409: VenusErrorResponse
    /**
     * Unprocessable Entity
     */
    422: VenusErrorResponse
}

export type VenusPutArtistCoverArtError =
    VenusPutArtistCoverArtErrors[keyof VenusPutArtistCoverArtErrors]

export type VenusPutArtistCoverArtResponses = {
    /**
     * Successful Response
     */
    200: unknown
}

export type VenusGetArtistAlbumsData = {
    body?: never
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null
    }
    path: {
        /**
         * Artist Id
         */
        artist_id: number
    }
    query?: never
    url: "/library/artists/{artist_id}/albums"
}

export type VenusGetArtistAlbumsErrors = {
    /**
     * Bad Request
     */
    400: VenusErrorResponse
    /**
     * Unauthorized
     */
    401: VenusErrorResponse
    /**
     * Forbidden
     */
    403: VenusErrorResponse
    /**
     * Not Found
     */
    404: VenusErrorResponse
    /**
     * Conflict
     */
    409: VenusErrorResponse
    /**
     * Unprocessable Entity
     */
    422: VenusErrorResponse
}

export type VenusGetArtistAlbumsError =
    VenusGetArtistAlbumsErrors[keyof VenusGetArtistAlbumsErrors]

export type VenusGetArtistAlbumsResponses = {
    /**
     * Successful Response
     */
    200: AlbumsResponse
}

export type VenusGetArtistAlbumsResponse =
    VenusGetArtistAlbumsResponses[keyof VenusGetArtistAlbumsResponses]

export type VenusGetArtistTracksData = {
    body?: never
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null
    }
    path: {
        /**
         * Artist Id
         */
        artist_id: number
    }
    query?: never
    url: "/library/artists/{artist_id}/tracks"
}

export type VenusGetArtistTracksErrors = {
    /**
     * Bad Request
     */
    400: VenusErrorResponse
    /**
     * Unauthorized
     */
    401: VenusErrorResponse
    /**
     * Forbidden
     */
    403: VenusErrorResponse
    /**
     * Not Found
     */
    404: VenusErrorResponse
    /**
     * Conflict
     */
    409: VenusErrorResponse
    /**
     * Unprocessable Entity
     */
    422: VenusErrorResponse
}

export type VenusGetArtistTracksError =
    VenusGetArtistTracksErrors[keyof VenusGetArtistTracksErrors]

export type VenusGetArtistTracksResponses = {
    /**
     * Successful Response
     */
    200: TracksResponse
}

export type VenusGetArtistTracksResponse =
    VenusGetArtistTracksResponses[keyof VenusGetArtistTracksResponses]

export type VenusGetArtistWritingCreditsData = {
    body?: never
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null
    }
    path: {
        /**
         * Artist Id
         */
        artist_id: number
    }
    query?: never
    url: "/library/artists/{artist_id}/writing_credits"
}

export type VenusGetArtistWritingCreditsErrors = {
    /**
     * Bad Request
     */
    400: VenusErrorResponse
    /**
     * Unauthorized
     */
    401: VenusErrorResponse
    /**
     * Forbidden
     */
    403: VenusErrorResponse
    /**
     * Not Found
     */
    404: VenusErrorResponse
    /**
     * Conflict
     */
    409: VenusErrorResponse
    /**
     * Unprocessable Entity
     */
    422: VenusErrorResponse
}

export type VenusGetArtistWritingCreditsError =
    VenusGetArtistWritingCreditsErrors[keyof VenusGetArtistWritingCreditsErrors]

export type VenusGetArtistWritingCreditsResponses = {
    /**
     * Successful Response
     */
    200: TracksResponse
}

export type VenusGetArtistWritingCreditsResponse =
    VenusGetArtistWritingCreditsResponses[keyof VenusGetArtistWritingCreditsResponses]

export type VenusGetArtistProductionCreditsData = {
    body?: never
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null
    }
    path: {
        /**
         * Artist Id
         */
        artist_id: number
    }
    query?: never
    url: "/library/artists/{artist_id}/production_credits"
}

export type VenusGetArtistProductionCreditsErrors = {
    /**
     * Bad Request
     */
    400: VenusErrorResponse
    /**
     * Unauthorized
     */
    401: VenusErrorResponse
    /**
     * Forbidden
     */
    403: VenusErrorResponse
    /**
     * Not Found
     */
    404: VenusErrorResponse
    /**
     * Conflict
     */
    409: VenusErrorResponse
    /**
     * Unprocessable Entity
     */
    422: VenusErrorResponse
}

export type VenusGetArtistProductionCreditsError =
    VenusGetArtistProductionCreditsErrors[keyof VenusGetArtistProductionCreditsErrors]

export type VenusGetArtistProductionCreditsResponses = {
    /**
     * Successful Response
     */
    200: TracksResponse
}

export type VenusGetArtistProductionCreditsResponse =
    VenusGetArtistProductionCreditsResponses[keyof VenusGetArtistProductionCreditsResponses]

export type VenusGetArtistFeaturesData = {
    body?: never
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null
    }
    path: {
        /**
         * Artist Id
         */
        artist_id: number
    }
    query?: never
    url: "/library/artists/{artist_id}/features"
}

export type VenusGetArtistFeaturesErrors = {
    /**
     * Bad Request
     */
    400: VenusErrorResponse
    /**
     * Unauthorized
     */
    401: VenusErrorResponse
    /**
     * Forbidden
     */
    403: VenusErrorResponse
    /**
     * Not Found
     */
    404: VenusErrorResponse
    /**
     * Conflict
     */
    409: VenusErrorResponse
    /**
     * Unprocessable Entity
     */
    422: VenusErrorResponse
}

export type VenusGetArtistFeaturesError =
    VenusGetArtistFeaturesErrors[keyof VenusGetArtistFeaturesErrors]

export type VenusGetArtistFeaturesResponses = {
    /**
     * Successful Response
     */
    200: TracksResponse
}

export type VenusGetArtistFeaturesResponse =
    VenusGetArtistFeaturesResponses[keyof VenusGetArtistFeaturesResponses]

export type VenusGetArtistRemixesData = {
    body?: never
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null
    }
    path: {
        /**
         * Artist Id
         */
        artist_id: number
    }
    query?: never
    url: "/library/artists/{artist_id}/remixes"
}

export type VenusGetArtistRemixesErrors = {
    /**
     * Bad Request
     */
    400: VenusErrorResponse
    /**
     * Unauthorized
     */
    401: VenusErrorResponse
    /**
     * Forbidden
     */
    403: VenusErrorResponse
    /**
     * Not Found
     */
    404: VenusErrorResponse
    /**
     * Conflict
     */
    409: VenusErrorResponse
    /**
     * Unprocessable Entity
     */
    422: VenusErrorResponse
}

export type VenusGetArtistRemixesError =
    VenusGetArtistRemixesErrors[keyof VenusGetArtistRemixesErrors]

export type VenusGetArtistRemixesResponses = {
    /**
     * Successful Response
     */
    200: TracksResponse
}

export type VenusGetArtistRemixesResponse =
    VenusGetArtistRemixesResponses[keyof VenusGetArtistRemixesResponses]

export type VenusGetAlbumsData = {
    body?: never
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null
    }
    path?: never
    query?: never
    url: "/library/albums"
}

export type VenusGetAlbumsErrors = {
    /**
     * Bad Request
     */
    400: VenusErrorResponse
    /**
     * Unauthorized
     */
    401: VenusErrorResponse
    /**
     * Forbidden
     */
    403: VenusErrorResponse
    /**
     * Not Found
     */
    404: VenusErrorResponse
    /**
     * Conflict
     */
    409: VenusErrorResponse
    /**
     * Unprocessable Entity
     */
    422: VenusErrorResponse
}

export type VenusGetAlbumsError =
    VenusGetAlbumsErrors[keyof VenusGetAlbumsErrors]

export type VenusGetAlbumsResponses = {
    /**
     * Successful Response
     */
    200: AlbumsResponse
}

export type VenusGetAlbumsResponse =
    VenusGetAlbumsResponses[keyof VenusGetAlbumsResponses]

export type VenusGetAlbumData = {
    body?: never
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null
    }
    path: {
        /**
         * Album Id
         */
        album_id: number
    }
    query?: never
    url: "/library/albums/{album_id}"
}

export type VenusGetAlbumErrors = {
    /**
     * Bad Request
     */
    400: VenusErrorResponse
    /**
     * Unauthorized
     */
    401: VenusErrorResponse
    /**
     * Forbidden
     */
    403: VenusErrorResponse
    /**
     * Not Found
     */
    404: VenusErrorResponse
    /**
     * Conflict
     */
    409: VenusErrorResponse
    /**
     * Unprocessable Entity
     */
    422: VenusErrorResponse
}

export type VenusGetAlbumError = VenusGetAlbumErrors[keyof VenusGetAlbumErrors]

export type VenusGetAlbumResponses = {
    /**
     * Successful Response
     */
    200: AlbumWithDetailsDto
}

export type VenusGetAlbumResponse =
    VenusGetAlbumResponses[keyof VenusGetAlbumResponses]

export type VenusGetAlbumDiscsData = {
    body?: never
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null
    }
    path: {
        /**
         * Album Id
         */
        album_id: number
    }
    query?: never
    url: "/library/albums/{album_id}/discs"
}

export type VenusGetAlbumDiscsErrors = {
    /**
     * Bad Request
     */
    400: VenusErrorResponse
    /**
     * Unauthorized
     */
    401: VenusErrorResponse
    /**
     * Forbidden
     */
    403: VenusErrorResponse
    /**
     * Not Found
     */
    404: VenusErrorResponse
    /**
     * Conflict
     */
    409: VenusErrorResponse
    /**
     * Unprocessable Entity
     */
    422: VenusErrorResponse
}

export type VenusGetAlbumDiscsError =
    VenusGetAlbumDiscsErrors[keyof VenusGetAlbumDiscsErrors]

export type VenusGetAlbumDiscsResponses = {
    /**
     * Successful Response
     */
    200: DiscsResponse
}

export type VenusGetAlbumDiscsResponse =
    VenusGetAlbumDiscsResponses[keyof VenusGetAlbumDiscsResponses]

export type VenusGetAlbumDiscData = {
    body?: never
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null
    }
    path: {
        /**
         * Album Id
         */
        album_id: number
        /**
         * Disc Id
         */
        disc_id: number
    }
    query?: never
    url: "/library/albums/{album_id}/discs/{disc_id}"
}

export type VenusGetAlbumDiscErrors = {
    /**
     * Bad Request
     */
    400: VenusErrorResponse
    /**
     * Unauthorized
     */
    401: VenusErrorResponse
    /**
     * Forbidden
     */
    403: VenusErrorResponse
    /**
     * Not Found
     */
    404: VenusErrorResponse
    /**
     * Conflict
     */
    409: VenusErrorResponse
    /**
     * Unprocessable Entity
     */
    422: VenusErrorResponse
}

export type VenusGetAlbumDiscError =
    VenusGetAlbumDiscErrors[keyof VenusGetAlbumDiscErrors]

export type VenusGetAlbumDiscResponses = {
    /**
     * Successful Response
     */
    200: DiscDto
}

export type VenusGetAlbumDiscResponse =
    VenusGetAlbumDiscResponses[keyof VenusGetAlbumDiscResponses]

export type VenusGetAlbumDiscTracksData = {
    body?: never
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null
    }
    path: {
        /**
         * Album Id
         */
        album_id: number
        /**
         * Disc Id
         */
        disc_id: number
    }
    query?: never
    url: "/library/albums/{album_id}/discs/{disc_id}/tracks"
}

export type VenusGetAlbumDiscTracksErrors = {
    /**
     * Bad Request
     */
    400: VenusErrorResponse
    /**
     * Unauthorized
     */
    401: VenusErrorResponse
    /**
     * Forbidden
     */
    403: VenusErrorResponse
    /**
     * Not Found
     */
    404: VenusErrorResponse
    /**
     * Conflict
     */
    409: VenusErrorResponse
    /**
     * Unprocessable Entity
     */
    422: VenusErrorResponse
}

export type VenusGetAlbumDiscTracksError =
    VenusGetAlbumDiscTracksErrors[keyof VenusGetAlbumDiscTracksErrors]

export type VenusGetAlbumDiscTracksResponses = {
    /**
     * Successful Response
     */
    200: TracksResponse
}

export type VenusGetAlbumDiscTracksResponse =
    VenusGetAlbumDiscTracksResponses[keyof VenusGetAlbumDiscTracksResponses]

export type VenusGetAlbumArtworkData = {
    body?: never
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null
    }
    path: {
        /**
         * Album Id
         */
        album_id: number
    }
    query?: never
    url: "/library/albums/{album_id}/artwork"
}

export type VenusGetAlbumArtworkErrors = {
    /**
     * Bad Request
     */
    400: VenusErrorResponse
    /**
     * Unauthorized
     */
    401: VenusErrorResponse
    /**
     * Forbidden
     */
    403: VenusErrorResponse
    /**
     * Not Found
     */
    404: VenusErrorResponse
    /**
     * Conflict
     */
    409: VenusErrorResponse
    /**
     * Unprocessable Entity
     */
    422: VenusErrorResponse
}

export type VenusGetAlbumArtworkError =
    VenusGetAlbumArtworkErrors[keyof VenusGetAlbumArtworkErrors]

export type VenusGetAlbumArtworkResponses = {
    /**
     * Successful Response
     */
    200: unknown
}

export type VenusGetTracksData = {
    body?: never
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null
    }
    path?: never
    query?: never
    url: "/library/tracks"
}

export type VenusGetTracksErrors = {
    /**
     * Bad Request
     */
    400: VenusErrorResponse
    /**
     * Unauthorized
     */
    401: VenusErrorResponse
    /**
     * Forbidden
     */
    403: VenusErrorResponse
    /**
     * Not Found
     */
    404: VenusErrorResponse
    /**
     * Conflict
     */
    409: VenusErrorResponse
    /**
     * Unprocessable Entity
     */
    422: VenusErrorResponse
}

export type VenusGetTracksError =
    VenusGetTracksErrors[keyof VenusGetTracksErrors]

export type VenusGetTracksResponses = {
    /**
     * Successful Response
     */
    200: TracksResponse
}

export type VenusGetTracksResponse =
    VenusGetTracksResponses[keyof VenusGetTracksResponses]

export type VenusGetTrackData = {
    body?: never
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null
    }
    path: {
        /**
         * Track Id
         */
        track_id: number
    }
    query?: never
    url: "/library/tracks/{track_id}"
}

export type VenusGetTrackErrors = {
    /**
     * Bad Request
     */
    400: VenusErrorResponse
    /**
     * Unauthorized
     */
    401: VenusErrorResponse
    /**
     * Forbidden
     */
    403: VenusErrorResponse
    /**
     * Not Found
     */
    404: VenusErrorResponse
    /**
     * Conflict
     */
    409: VenusErrorResponse
    /**
     * Unprocessable Entity
     */
    422: VenusErrorResponse
}

export type VenusGetTrackError = VenusGetTrackErrors[keyof VenusGetTrackErrors]

export type VenusGetTrackResponses = {
    /**
     * Successful Response
     */
    200: TrackDto
}

export type VenusGetTrackResponse =
    VenusGetTrackResponses[keyof VenusGetTrackResponses]

export type VenusGetTrackOriginalStreamData = {
    body?: never
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null
    }
    path: {
        /**
         * Track Id
         */
        track_id: number
    }
    query?: never
    url: "/library/tracks/{track_id}/streams/original"
}

export type VenusGetTrackOriginalStreamErrors = {
    /**
     * Bad Request
     */
    400: VenusErrorResponse
    /**
     * Unauthorized
     */
    401: VenusErrorResponse
    /**
     * Forbidden
     */
    403: VenusErrorResponse
    /**
     * Not Found
     */
    404: VenusErrorResponse
    /**
     * Conflict
     */
    409: VenusErrorResponse
    /**
     * Unprocessable Entity
     */
    422: VenusErrorResponse
}

export type VenusGetTrackOriginalStreamError =
    VenusGetTrackOriginalStreamErrors[keyof VenusGetTrackOriginalStreamErrors]

export type VenusGetTrackOriginalStreamResponses = {
    /**
     * Successful Response
     */
    200: unknown
}

export type VenusGetTrackWaveformData = {
    body?: never
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null
    }
    path: {
        /**
         * Track Id
         */
        track_id: number
    }
    query?: never
    url: "/library/tracks/{track_id}/waveform"
}

export type VenusGetTrackWaveformErrors = {
    /**
     * Bad Request
     */
    400: VenusErrorResponse
    /**
     * Unauthorized
     */
    401: VenusErrorResponse
    /**
     * Forbidden
     */
    403: VenusErrorResponse
    /**
     * Not Found
     */
    404: VenusErrorResponse
    /**
     * Conflict
     */
    409: VenusErrorResponse
    /**
     * Unprocessable Entity
     */
    422: VenusErrorResponse
}

export type VenusGetTrackWaveformError =
    VenusGetTrackWaveformErrors[keyof VenusGetTrackWaveformErrors]

export type VenusGetTrackWaveformResponses = {
    /**
     * Successful Response
     */
    200: TrackWaveformDto
}

export type VenusGetTrackWaveformResponse =
    VenusGetTrackWaveformResponses[keyof VenusGetTrackWaveformResponses]

export type VenusGetTrackLyricsData = {
    body?: never
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null
    }
    path: {
        /**
         * Track Id
         */
        track_id: number
    }
    query?: never
    url: "/library/tracks/{track_id}/lyrics"
}

export type VenusGetTrackLyricsErrors = {
    /**
     * Bad Request
     */
    400: VenusErrorResponse
    /**
     * Unauthorized
     */
    401: VenusErrorResponse
    /**
     * Forbidden
     */
    403: VenusErrorResponse
    /**
     * Not Found
     */
    404: VenusErrorResponse
    /**
     * Conflict
     */
    409: VenusErrorResponse
    /**
     * Unprocessable Entity
     */
    422: VenusErrorResponse
}

export type VenusGetTrackLyricsError =
    VenusGetTrackLyricsErrors[keyof VenusGetTrackLyricsErrors]

export type VenusGetTrackLyricsResponses = {
    /**
     * Successful Response
     */
    200: TrackLyricsDto
}

export type VenusGetTrackLyricsResponse =
    VenusGetTrackLyricsResponses[keyof VenusGetTrackLyricsResponses]

export type VenusGetCoverArtData = {
    body?: never
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null
    }
    path: {
        /**
         * Cover Art Id
         */
        cover_art_id: number
    }
    query?: never
    url: "/library/cover-arts/{cover_art_id}"
}

export type VenusGetCoverArtErrors = {
    /**
     * Bad Request
     */
    400: VenusErrorResponse
    /**
     * Unauthorized
     */
    401: VenusErrorResponse
    /**
     * Forbidden
     */
    403: VenusErrorResponse
    /**
     * Not Found
     */
    404: VenusErrorResponse
    /**
     * Conflict
     */
    409: VenusErrorResponse
    /**
     * Unprocessable Entity
     */
    422: VenusErrorResponse
}

export type VenusGetCoverArtError =
    VenusGetCoverArtErrors[keyof VenusGetCoverArtErrors]

export type VenusGetCoverArtResponses = {
    /**
     * Successful Response
     */
    200: unknown
}

export type VenusGetNoSplitEntriesData = {
    body?: never
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null
    }
    path?: never
    query?: never
    url: "/metadata/no-split-list"
}

export type VenusGetNoSplitEntriesErrors = {
    /**
     * Bad Request
     */
    400: VenusErrorResponse
    /**
     * Unauthorized
     */
    401: VenusErrorResponse
    /**
     * Forbidden
     */
    403: VenusErrorResponse
    /**
     * Not Found
     */
    404: VenusErrorResponse
    /**
     * Conflict
     */
    409: VenusErrorResponse
    /**
     * Unprocessable Entity
     */
    422: VenusErrorResponse
}

export type VenusGetNoSplitEntriesError =
    VenusGetNoSplitEntriesErrors[keyof VenusGetNoSplitEntriesErrors]

export type VenusGetNoSplitEntriesResponses = {
    /**
     * Successful Response
     */
    200: NoSplitEntriesResponse
}

export type VenusGetNoSplitEntriesResponse =
    VenusGetNoSplitEntriesResponses[keyof VenusGetNoSplitEntriesResponses]

export type VenusCreateNoSplitEntryData = {
    body: NoSplitUpsertRequest
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null
    }
    path?: never
    query?: never
    url: "/metadata/no-split-list"
}

export type VenusCreateNoSplitEntryErrors = {
    /**
     * Bad Request
     */
    400: VenusErrorResponse
    /**
     * Unauthorized
     */
    401: VenusErrorResponse
    /**
     * Forbidden
     */
    403: VenusErrorResponse
    /**
     * Not Found
     */
    404: VenusErrorResponse
    /**
     * Conflict
     */
    409: VenusErrorResponse
    /**
     * Unprocessable Entity
     */
    422: VenusErrorResponse
}

export type VenusCreateNoSplitEntryError =
    VenusCreateNoSplitEntryErrors[keyof VenusCreateNoSplitEntryErrors]

export type VenusCreateNoSplitEntryResponses = {
    /**
     * Successful Response
     */
    200: NoSplitEntryDto
}

export type VenusCreateNoSplitEntryResponse =
    VenusCreateNoSplitEntryResponses[keyof VenusCreateNoSplitEntryResponses]

export type VenusDeleteNoSplitEntryData = {
    body?: never
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null
    }
    path: {
        /**
         * Entry Id
         */
        entry_id: number
    }
    query?: never
    url: "/metadata/no-split-list/{entry_id}"
}

export type VenusDeleteNoSplitEntryErrors = {
    /**
     * Bad Request
     */
    400: VenusErrorResponse
    /**
     * Unauthorized
     */
    401: VenusErrorResponse
    /**
     * Forbidden
     */
    403: VenusErrorResponse
    /**
     * Not Found
     */
    404: VenusErrorResponse
    /**
     * Conflict
     */
    409: VenusErrorResponse
    /**
     * Unprocessable Entity
     */
    422: VenusErrorResponse
}

export type VenusDeleteNoSplitEntryError =
    VenusDeleteNoSplitEntryErrors[keyof VenusDeleteNoSplitEntryErrors]

export type VenusDeleteNoSplitEntryResponses = {
    /**
     * Successful Response
     */
    200: unknown
}

export type VenusUpdateNoSplitEntryData = {
    body: NoSplitUpsertRequest
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null
    }
    path: {
        /**
         * Entry Id
         */
        entry_id: number
    }
    query?: never
    url: "/metadata/no-split-list/{entry_id}"
}

export type VenusUpdateNoSplitEntryErrors = {
    /**
     * Bad Request
     */
    400: VenusErrorResponse
    /**
     * Unauthorized
     */
    401: VenusErrorResponse
    /**
     * Forbidden
     */
    403: VenusErrorResponse
    /**
     * Not Found
     */
    404: VenusErrorResponse
    /**
     * Conflict
     */
    409: VenusErrorResponse
    /**
     * Unprocessable Entity
     */
    422: VenusErrorResponse
}

export type VenusUpdateNoSplitEntryError =
    VenusUpdateNoSplitEntryErrors[keyof VenusUpdateNoSplitEntryErrors]

export type VenusUpdateNoSplitEntryResponses = {
    /**
     * Successful Response
     */
    200: NoSplitEntryDto
}

export type VenusUpdateNoSplitEntryResponse =
    VenusUpdateNoSplitEntryResponses[keyof VenusUpdateNoSplitEntryResponses]

export type VenusGetScanSettingsData = {
    body?: never
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null
    }
    path?: never
    query?: never
    url: "/settings/scanning"
}

export type VenusGetScanSettingsErrors = {
    /**
     * Bad Request
     */
    400: VenusErrorResponse
    /**
     * Unauthorized
     */
    401: VenusErrorResponse
    /**
     * Forbidden
     */
    403: VenusErrorResponse
    /**
     * Not Found
     */
    404: VenusErrorResponse
    /**
     * Conflict
     */
    409: VenusErrorResponse
    /**
     * Unprocessable Entity
     */
    422: VenusErrorResponse
}

export type VenusGetScanSettingsError =
    VenusGetScanSettingsErrors[keyof VenusGetScanSettingsErrors]

export type VenusGetScanSettingsResponses = {
    /**
     * Successful Response
     */
    200: ScanSettingsDto
}

export type VenusGetScanSettingsResponse =
    VenusGetScanSettingsResponses[keyof VenusGetScanSettingsResponses]

export type VenusUpdateScanSettingsData = {
    body: ScanSettingsUpdateRequest
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null
    }
    path?: never
    query?: never
    url: "/settings/scanning"
}

export type VenusUpdateScanSettingsErrors = {
    /**
     * Bad Request
     */
    400: VenusErrorResponse
    /**
     * Unauthorized
     */
    401: VenusErrorResponse
    /**
     * Forbidden
     */
    403: VenusErrorResponse
    /**
     * Not Found
     */
    404: VenusErrorResponse
    /**
     * Conflict
     */
    409: VenusErrorResponse
    /**
     * Unprocessable Entity
     */
    422: VenusErrorResponse
}

export type VenusUpdateScanSettingsError =
    VenusUpdateScanSettingsErrors[keyof VenusUpdateScanSettingsErrors]

export type VenusUpdateScanSettingsResponses = {
    /**
     * Successful Response
     */
    200: ScanSettingsDto
}

export type VenusUpdateScanSettingsResponse =
    VenusUpdateScanSettingsResponses[keyof VenusUpdateScanSettingsResponses]

export type VenusGetLyricsSettingsData = {
    body?: never
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null
    }
    path?: never
    query?: never
    url: "/settings/lyrics"
}

export type VenusGetLyricsSettingsErrors = {
    /**
     * Bad Request
     */
    400: VenusErrorResponse
    /**
     * Unauthorized
     */
    401: VenusErrorResponse
    /**
     * Forbidden
     */
    403: VenusErrorResponse
    /**
     * Not Found
     */
    404: VenusErrorResponse
    /**
     * Conflict
     */
    409: VenusErrorResponse
    /**
     * Unprocessable Entity
     */
    422: VenusErrorResponse
}

export type VenusGetLyricsSettingsError =
    VenusGetLyricsSettingsErrors[keyof VenusGetLyricsSettingsErrors]

export type VenusGetLyricsSettingsResponses = {
    /**
     * Successful Response
     */
    200: LyricsSettingsDto
}

export type VenusGetLyricsSettingsResponse =
    VenusGetLyricsSettingsResponses[keyof VenusGetLyricsSettingsResponses]

export type VenusUpdateLyricsSettingsData = {
    body: LyricsSettingsUpdateRequest
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null
    }
    path?: never
    query?: never
    url: "/settings/lyrics"
}

export type VenusUpdateLyricsSettingsErrors = {
    /**
     * Bad Request
     */
    400: VenusErrorResponse
    /**
     * Unauthorized
     */
    401: VenusErrorResponse
    /**
     * Forbidden
     */
    403: VenusErrorResponse
    /**
     * Not Found
     */
    404: VenusErrorResponse
    /**
     * Conflict
     */
    409: VenusErrorResponse
    /**
     * Unprocessable Entity
     */
    422: VenusErrorResponse
}

export type VenusUpdateLyricsSettingsError =
    VenusUpdateLyricsSettingsErrors[keyof VenusUpdateLyricsSettingsErrors]

export type VenusUpdateLyricsSettingsResponses = {
    /**
     * Successful Response
     */
    200: LyricsSettingsDto
}

export type VenusUpdateLyricsSettingsResponse =
    VenusUpdateLyricsSettingsResponses[keyof VenusUpdateLyricsSettingsResponses]

export type VenusGetMusicalAnalysisSettingsData = {
    body?: never
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null
    }
    path?: never
    query?: never
    url: "/settings/musical_analysis"
}

export type VenusGetMusicalAnalysisSettingsErrors = {
    /**
     * Bad Request
     */
    400: VenusErrorResponse
    /**
     * Unauthorized
     */
    401: VenusErrorResponse
    /**
     * Forbidden
     */
    403: VenusErrorResponse
    /**
     * Not Found
     */
    404: VenusErrorResponse
    /**
     * Conflict
     */
    409: VenusErrorResponse
    /**
     * Unprocessable Entity
     */
    422: VenusErrorResponse
}

export type VenusGetMusicalAnalysisSettingsError =
    VenusGetMusicalAnalysisSettingsErrors[keyof VenusGetMusicalAnalysisSettingsErrors]

export type VenusGetMusicalAnalysisSettingsResponses = {
    /**
     * Successful Response
     */
    200: MusicalAnalysisSettingsDto
}

export type VenusGetMusicalAnalysisSettingsResponse =
    VenusGetMusicalAnalysisSettingsResponses[keyof VenusGetMusicalAnalysisSettingsResponses]

export type VenusUpdateMusicalAnalysisSettingsData = {
    body: MusicalAnalysisSettingsUpdateRequest
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null
    }
    path?: never
    query?: never
    url: "/settings/musical_analysis"
}

export type VenusUpdateMusicalAnalysisSettingsErrors = {
    /**
     * Bad Request
     */
    400: VenusErrorResponse
    /**
     * Unauthorized
     */
    401: VenusErrorResponse
    /**
     * Forbidden
     */
    403: VenusErrorResponse
    /**
     * Not Found
     */
    404: VenusErrorResponse
    /**
     * Conflict
     */
    409: VenusErrorResponse
    /**
     * Unprocessable Entity
     */
    422: VenusErrorResponse
}

export type VenusUpdateMusicalAnalysisSettingsError =
    VenusUpdateMusicalAnalysisSettingsErrors[keyof VenusUpdateMusicalAnalysisSettingsErrors]

export type VenusUpdateMusicalAnalysisSettingsResponses = {
    /**
     * Successful Response
     */
    200: MusicalAnalysisSettingsDto
}

export type VenusUpdateMusicalAnalysisSettingsResponse =
    VenusUpdateMusicalAnalysisSettingsResponses[keyof VenusUpdateMusicalAnalysisSettingsResponses]

export type VenusGetMusicbrainzSettingsData = {
    body?: never
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null
    }
    path?: never
    query?: never
    url: "/settings/musicbrainz"
}

export type VenusGetMusicbrainzSettingsErrors = {
    /**
     * Bad Request
     */
    400: VenusErrorResponse
    /**
     * Unauthorized
     */
    401: VenusErrorResponse
    /**
     * Forbidden
     */
    403: VenusErrorResponse
    /**
     * Not Found
     */
    404: VenusErrorResponse
    /**
     * Conflict
     */
    409: VenusErrorResponse
    /**
     * Unprocessable Entity
     */
    422: VenusErrorResponse
}

export type VenusGetMusicbrainzSettingsError =
    VenusGetMusicbrainzSettingsErrors[keyof VenusGetMusicbrainzSettingsErrors]

export type VenusGetMusicbrainzSettingsResponses = {
    /**
     * Successful Response
     */
    200: MusicbrainzSettingsDto
}

export type VenusGetMusicbrainzSettingsResponse =
    VenusGetMusicbrainzSettingsResponses[keyof VenusGetMusicbrainzSettingsResponses]

export type VenusUpdateMusicbrainzSettingsData = {
    body: MusicbrainzSettingsUpdateRequest
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null
    }
    path?: never
    query?: never
    url: "/settings/musicbrainz"
}

export type VenusUpdateMusicbrainzSettingsErrors = {
    /**
     * Bad Request
     */
    400: VenusErrorResponse
    /**
     * Unauthorized
     */
    401: VenusErrorResponse
    /**
     * Forbidden
     */
    403: VenusErrorResponse
    /**
     * Not Found
     */
    404: VenusErrorResponse
    /**
     * Conflict
     */
    409: VenusErrorResponse
    /**
     * Unprocessable Entity
     */
    422: VenusErrorResponse
}

export type VenusUpdateMusicbrainzSettingsError =
    VenusUpdateMusicbrainzSettingsErrors[keyof VenusUpdateMusicbrainzSettingsErrors]

export type VenusUpdateMusicbrainzSettingsResponses = {
    /**
     * Successful Response
     */
    200: MusicbrainzSettingsDto
}

export type VenusUpdateMusicbrainzSettingsResponse =
    VenusUpdateMusicbrainzSettingsResponses[keyof VenusUpdateMusicbrainzSettingsResponses]

export type VenusGetPlaylistsData = {
    body?: never
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null
    }
    path?: never
    query?: never
    url: "/playlists"
}

export type VenusGetPlaylistsErrors = {
    /**
     * Bad Request
     */
    400: VenusErrorResponse
    /**
     * Unauthorized
     */
    401: VenusErrorResponse
    /**
     * Forbidden
     */
    403: VenusErrorResponse
    /**
     * Not Found
     */
    404: VenusErrorResponse
    /**
     * Conflict
     */
    409: VenusErrorResponse
    /**
     * Unprocessable Entity
     */
    422: VenusErrorResponse
}

export type VenusGetPlaylistsError =
    VenusGetPlaylistsErrors[keyof VenusGetPlaylistsErrors]

export type VenusGetPlaylistsResponses = {
    /**
     * Successful Response
     */
    200: PlaylistsResponse
}

export type VenusGetPlaylistsResponse =
    VenusGetPlaylistsResponses[keyof VenusGetPlaylistsResponses]

export type VenusCreatePlaylistData = {
    body: PlaylistCreateRequest
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null
    }
    path?: never
    query?: never
    url: "/playlists"
}

export type VenusCreatePlaylistErrors = {
    /**
     * Bad Request
     */
    400: VenusErrorResponse
    /**
     * Unauthorized
     */
    401: VenusErrorResponse
    /**
     * Forbidden
     */
    403: VenusErrorResponse
    /**
     * Not Found
     */
    404: VenusErrorResponse
    /**
     * Conflict
     */
    409: VenusErrorResponse
    /**
     * Unprocessable Entity
     */
    422: VenusErrorResponse
}

export type VenusCreatePlaylistError =
    VenusCreatePlaylistErrors[keyof VenusCreatePlaylistErrors]

export type VenusCreatePlaylistResponses = {
    /**
     * Successful Response
     */
    200: PlaylistDto
}

export type VenusCreatePlaylistResponse =
    VenusCreatePlaylistResponses[keyof VenusCreatePlaylistResponses]

export type VenusGetPlaylistByIdData = {
    body?: never
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null
    }
    path: {
        /**
         * Playlist Id
         */
        playlist_id: number
    }
    query?: never
    url: "/playlists/{playlist_id}"
}

export type VenusGetPlaylistByIdErrors = {
    /**
     * Bad Request
     */
    400: VenusErrorResponse
    /**
     * Unauthorized
     */
    401: VenusErrorResponse
    /**
     * Forbidden
     */
    403: VenusErrorResponse
    /**
     * Not Found
     */
    404: VenusErrorResponse
    /**
     * Conflict
     */
    409: VenusErrorResponse
    /**
     * Unprocessable Entity
     */
    422: VenusErrorResponse
}

export type VenusGetPlaylistByIdError =
    VenusGetPlaylistByIdErrors[keyof VenusGetPlaylistByIdErrors]

export type VenusGetPlaylistByIdResponses = {
    /**
     * Successful Response
     */
    200: PlaylistWithTracksDto
}

export type VenusGetPlaylistByIdResponse =
    VenusGetPlaylistByIdResponses[keyof VenusGetPlaylistByIdResponses]

export type VenusAddTrackToPlaylistData = {
    body: PlaylistAddTrackRequest
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null
    }
    path: {
        /**
         * Playlist Id
         */
        playlist_id: number
    }
    query?: never
    url: "/playlists/{playlist_id}/tracks"
}

export type VenusAddTrackToPlaylistErrors = {
    /**
     * Bad Request
     */
    400: VenusErrorResponse
    /**
     * Unauthorized
     */
    401: VenusErrorResponse
    /**
     * Forbidden
     */
    403: VenusErrorResponse
    /**
     * Not Found
     */
    404: VenusErrorResponse
    /**
     * Conflict
     */
    409: VenusErrorResponse
    /**
     * Unprocessable Entity
     */
    422: VenusErrorResponse
}

export type VenusAddTrackToPlaylistError =
    VenusAddTrackToPlaylistErrors[keyof VenusAddTrackToPlaylistErrors]

export type VenusAddTrackToPlaylistResponses = {
    /**
     * Successful Response
     */
    200: unknown
}

export type VenusDeleteTrackFromPlaylistData = {
    body?: never
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null
    }
    path: {
        /**
         * Playlist Id
         */
        playlist_id: number
        /**
         * Playlist Track Id
         */
        playlist_track_id: number
    }
    query?: never
    url: "/playlists/{playlist_id}/tracks/{playlist_track_id}"
}

export type VenusDeleteTrackFromPlaylistErrors = {
    /**
     * Bad Request
     */
    400: VenusErrorResponse
    /**
     * Unauthorized
     */
    401: VenusErrorResponse
    /**
     * Forbidden
     */
    403: VenusErrorResponse
    /**
     * Not Found
     */
    404: VenusErrorResponse
    /**
     * Conflict
     */
    409: VenusErrorResponse
    /**
     * Unprocessable Entity
     */
    422: VenusErrorResponse
}

export type VenusDeleteTrackFromPlaylistError =
    VenusDeleteTrackFromPlaylistErrors[keyof VenusDeleteTrackFromPlaylistErrors]

export type VenusDeleteTrackFromPlaylistResponses = {
    /**
     * Successful Response
     */
    200: unknown
}
